---
- name: configure devbox environment
  hosts: localhost
  tasks:
    - name: install devtools
      become: true
      yum:
        name:
          - buildah
          - skopeo
          - podman
          - git
          - zsh
          - vim-enhanced
          - neovim
          - binutils
          - gdb
          - gcc
          - gcc-c++
          - make
          - nodejs
          - python
          - fira-code-fonts
          - java-latest-openjdk
          - cmake
          - tmux
        state: present

    - name: deploy zsh
      import_tasks: tasks/zsh.yml

    - name: deploy vim
      import_tasks: tasks/vim.yml

    - name: deploy tmux
      import_tasks: tasks/tmux.yml
