---
- name: install tmux themepack
  git:
    repo: https://github.com/jimeh/tmux-themepack.git
    dest: "{{ ansible_env.HOME }}/.config/tmux-themepack"
    depth: 1

- name: deploy tmux configuration
  copy:
    src: tmux/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
