---
- name: install zsh packages
  become: yes
  yum:
    name:
      - zsh

- name: install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ '~' | expanduser }}/.local/share/oh-my-zsh"
    depth: 1

- name: install oh-my-zsh plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ '~' | expanduser }}/.local/share/oh-my-zsh/plugins/{{ item.name }}"
  loop:
    - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      name: zsh-syntax-highlighting
    - repo: https://github.com/zsh-users/zsh-autosuggestions.git
      name: zsh-autosuggestions

- name: install oh-my-zsh themes
  git:
    repo: "{{ item. repo }}"
    dest: "{{ '~' | expanduser }}/.local/share/oh-my-zsh/custom/themes/{{ item.name }}"
    depth: 1
  loop:
    - repo: https://github.com/romkatv/powerlevel10k.git
      name: powerlevel10k

- name: deploy prompt
  copy:
    src: zsh/p10k.zsh
    dest: "{{ '~' | expanduser }}/.local/share/p10k.zsh"

- name: deploy .zshrc
  copy:
    src: zsh/zshrc
    dest: "{{ '~' | expanduser }}/.zshrc"
