set -g prefix `
bind ` send-prefix
set -g update-environment "SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION"

# Load theme
source-file "$HOME/.config/tmux-themepack/powerline/default/red.tmuxtheme"
