use std::collections::HashMap;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone)]
pub struct ModuleEntry {
    pub name: String,
    pub loaded: bool,
    pub in_use: bool,
}

#[derive(Debug, Clone)]
pub struct LoadedInfo {
    pub size: u64,
    pub refcount: i64,
    pub users: Vec<String>,
}

impl LoadedInfo {
    pub fn in_use(&self) -> bool {
        self.refcount > 0 || !self.users.is_empty()
    }
}

pub fn kernel_release() -> io::Result<String> {
    fs::read_to_string("/proc/sys/kernel/osrelease").map(|s| s.trim().to_string())
}

pub fn list_loaded_modules() -> io::Result<HashMap<String, LoadedInfo>> {
    let content = fs::read_to_string("/proc/modules")?;
    let mut map = HashMap::new();
    for line in content.lines() {
        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() < 4 {
            continue;
        }
        let name = parts[0].to_string();
        let size = parts[1].parse().unwrap_or(0);
        let refcount = parts[2].parse().unwrap_or(0);
        let users = if parts[3] == "-" {
            Vec::new()
        } else {
            parts[3]
                .split(',')
                .filter(|s| !s.is_empty())
                .map(String::from)
                .collect()
        };
        map.insert(
            name,
            LoadedInfo {
                size,
                refcount,
                users,
            },
        );
    }
    Ok(map)
}

pub fn list_available_modules() -> io::Result<Vec<String>> {
    let release = kernel_release()?;
    let kernel_dir = PathBuf::from(format!("/lib/modules/{}/kernel", release));
    let mut names = Vec::new();
    walk_modules(&kernel_dir, &mut names)?;
    names.sort();
    names.dedup();
    Ok(names)
}

fn walk_modules(dir: &Path, out: &mut Vec<String>) -> io::Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            walk_modules(&path, out)?;
        } else if let Some(name) = module_name_from_path(&path) {
            out.push(name);
        }
    }
    Ok(())
}

fn module_name_from_path(p: &Path) -> Option<String> {
    let fname = p.file_name()?.to_str()?;
    let stripped = fname
        .strip_suffix(".ko")
        .or_else(|| fname.strip_suffix(".ko.xz"))
        .or_else(|| fname.strip_suffix(".ko.zst"))
        .or_else(|| fname.strip_suffix(".ko.gz"))?;
    Some(stripped.replace('-', "_"))
}

pub fn read_blacklist(path: &str) -> io::Result<Vec<String>> {
    let p = Path::new(path);
    if !p.exists() {
        return Ok(Vec::new());
    }
    let content = fs::read_to_string(p)?;
    let mut out = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some(rest) = line.strip_prefix("blacklist ") {
            let name = rest.trim().to_string();
            if !name.is_empty() {
                out.push(name);
            }
        }
    }
    Ok(out)
}

pub fn write_blacklist(path: &str, names: &[String]) -> io::Result<()> {
    let mut content = String::from("# Generated by kmod-blacklist\n");
    content.push_str("# Manual edits may be overwritten next time the tool saves.\n\n");
    for name in names {
        content.push_str(&format!("blacklist {}\n", name));
    }
    fs::write(path, content)
}
